# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [main]
    paths: ['Code/**', 'build-and-test.yml']
  pull_request:
    branches: [main]
    paths: ['Code/**', 'build-and-test.yml']

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Light.DataAccessMocks.sln
    - name: Build
      run: dotnet build ./Code/Light.DataAccessMocks.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./Code/Light.DataAccessMocks.Tests/Light.DataAccessMocks.Tests.csproj -c Release --no-build --verbosity normal
